# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install nodejs -qq
          npm install -g yarn
          yarn install
      - name: Build the site
        run: yarn build
      - name: Upload Artifact 1
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-build
          path: build/
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-build
          github_token: ${{ secrets.GITHUB_TOKEN }}
